services:
  expertsdr3-remote-server:
    image: ghcr.io/bi9bbl/expertsdr3-remote-server:latest
    container_name: ExpertSDR3-Remote-server
    ports:
      - "8080:8080"
    volumes:
      - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime:ro
      - $PWD/config.json:/app/config.json
